title: Kezheng Xiang # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <h4> About me </h4>
  <h5>I love what programming can do with data and want to apply my software development skills to learn interesting things from it.
  <br><br>
  I am a Data-Focused Software Developer. 
  <br><br>
  <p>Software developement Intern<p>, Busy Squirrels Company.(Jan 2021 – Present)
  <br><br>
  <p>Data Engineer Intern<p>, Overseas Student Services Corp.(May 2020 – Aug 2020 Remote)
  <br><br>
  <p>Research Assistant<p>,Fordham University(Sep 2019 - Dec 2020)
  <br><br>
  <p>Data Engineer Intern<p>,Hwadee Information Technology Corp.(May 2016-Aug 2016)
  <br><br></h5>
  <a href="https://www.linkedin.com/feed/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
