title: Kezheng Xiang # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 I love what programming can do with data and want to apply my software development skills to learn interesting things from it.
  <br>
  I am a Data-Focused Software Engineer. 
  <br>
  Data Analyst Intern,Shoptaki Inc(July 2020-Present)
  <br>
  Research Assistant,Fordham University(Sep 2019-Present)
  <br>
  Data Engineer Intern,Hwadee Information Technology Corp.(May 2016-Aug 2016)
  <br><br>
  <a href="https://www.linkedin.com/feed/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-cayman
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
